# Mogulesko's entire autobiography dictated to the "Forverts" by Mogulesko himself

::: {style="text-align: right;"}
_Published in the_ Forverts _on [1914-02-05](https://www.nli.org.il/en/newspapers/frw/1914/02/05/01/article/17/)_
:::


> This chapter about his life in America, as he dictated to a reporter from the "Forverts" from his deathbed. -- How the Yiddish theater was born. -- Mogulesko was one of the very first performers.^[Except this is a lie - this is not actually what they publish here. They are playing readership games.]
<!--
Picture caption: 
Sigmond Mogulesko as "Frantsele" in the operetta "The capricious _meidl_" by Goldfaden. He appeared in this role when he was 17 years old.
-->

A few weeks before his death, Mogulesko started to tell this chapter of his memoirs, which takes place in America, to a reporter from the "Forverts." He was already lying in bed, a bed he no longer got up from. Our reporter wrote down everything Mogulesko told him. The actor told him, and our reporter recorded every word he said. His daughter was often nearby, and his wife would, from time to time, would comment things like, "Oy, how well you remember everything! _A gezund oif dich, tatele!_ You didn't forget the smallest, tiniest detail."

Our reporter had several conversations with Mogulesko about his life in America - from the first day that he arrived to now. The reporter would often ask him if the conversation was too much exertion for him.

"No," Mogulesko answered with his ever-charming little smile across his ailing face, "the opposite. It's bring me such joy, it's such a _mechiya_ to share these memories of the old, old days."

The first of these memories was Mogulesko's life in America, which we printed a few weeks ago. We'll continue those stories now, but first we want to make an announcement: We will re-publish Mogulesko's memories about the birth of the Yiddish theater, why he became an actor, and his earliest performances in Roumania and Russia. These memories were published in the "Forverts" a few years ago, and they are full of remarkably interesting tales of the Yiddish theater in general. Together with the new memories that he dictated on his deathbed, this comprises a complete biography of the late king of the Yiddish stage.

The first article that we're publishing here today was [first published in the "Forverts" on December 25th, 1909](https://www.nli.org.il/en/newspapers/frw/1909/12/25/01/article/33/). We are re-publishing it without any changes, with all dates as numbered as they originally appeared.

---

The famous Yiddish comedian Zelig Mogulesko has performed on the Yiddish stage for 33 years, first appearing from the very first moments of Yiddish theater's life. And from those very first moments until now has been among the most talented to appear. His biography is indeed the biography of the Yiddish theater itself.

A reporters from the "Forverts" arranged to speak with Mogulesko about these 33 years. Over the course of several such interviews, the stories Mogulesko are intereting not only because of his love for the Yiddish theater itself and Mogulesko's talents in particular, but also as general reading. He answered our questions with such vidid imagery and character portraits, with the tragedy and comedy of Jewish life, full of color and spirit.

We will quote his exact words as much as possible. He wanted to begin with the story of how he became an actor, but the writer asked him to begin earlier than that.

Mogulesko considered this, and a smile came across his face - one of his classic little smiles which brings such joy to the theater - and then he said said with astonishment, "You mean my childhood years? What do people need to hear about this for? Why would that be of interest?"

We resasured him that everything about his life is interesting, and then he began with an air of excitement about him:

"My father was a factory worker in a small _shtetele_ near [Zlatopoliye](https://en.wikipedia.org/wiki/Zlatopil,_Novomyrhorod)."

"What was the _shtetl_ called?" the reporter asked.

"Damned if I remember it..." he answered knitting his brow and racking his brain. "Ominsk!" He suddenly recalled. "But I remember Zlatopoliye very well, in the Kiev Governate. I am 51 years old^[seems like it's not relevant, but he definitely says this!]. My mother was a _meyukheses_^[well-born], the daughter of Laser Tschogol, a formidable man, a _balmoyfes_^[miracle-worker, essentially someone holy doing miracles in Chasidic context]. His brother, my uncle, was Avraham Zelig the _Katenker rav_^[unclear where the location e.g. "Katen" is]. I was named Zelig (Sigmond) after him. 


"My father died when I was nine years old. The city helped my mother out with a sort of pension, because she was the Rav's daughter. It wasn't enough to live on though, so she send me away to a _chazan_. I sang from a very young age there - I inherited this from my mother. She had a lovely voice and a good sense of music. She used to _kvell_ hearing me sing, but now out of desperation, she handed me over to the _chazan_ Yosef Heller. 

He had just arrived to Zlatopoliye from another city and had just begun to hold auditions, as was customary. His family had not yet come to the _shtetl_. People called him "the new _chazan_." I still remember my audition - he had me sing something and I sang a Belarusian song. He liked the song, but he said, 'Can you sing something _chazanishe_?' So I sang _M'khalkeil Chayim_^[a nigun, section of the second Amidah bracha. Who knows, could be the same tune we sing today.] and _Zochreinu_^[From Yom Kippur]."

"Were you self-conscious?" the reporter asked.

Mogulesko thought hard to recall, but could not.

"This I can't remember," he said. "Probably not. When it comes to singing or acting, I've never been shy. I've never had any stagefright.

"In any case, the _chazan_'s wife soon came in, and I was accepted for three years and given food and clothes, 30 rubles for rent, 5 rubles for the first year, 10 for the second, and 15 for the third year. By the way, this _chazan_ Yosef Heller died some time ago here in Philadelphia, and his widow lives there with her eight children. Eight years ago^[As this was originally published in 1909, we can assume this occurred ~1901], she married two of her daughters off in one evening, and I made a special trip down from New York to the wedding. While visiting I slept on the same pillows I used to sleep on in Zlatopoliye when I was just a nine year old _meshoyrer_^[synagogue choirboy].

Mogulesko then wanted to talk about the early days of the theater, but the reporter asked him to share a bit more from his _meshoyrer_ days. The actor's eyes lit up as he said, again with that smile, "Well, there's not much to say about those early days, When a young boy comes to a _chazan_, the first thing he does is stand still and stay quiet, and listen to the older _meshoyrim_ sing. He has to first learn the "trade." A little later once he has learned the _nigunim_, he can join the choir. That whole business didn't suit me much -- I wanted to finish my bread as quickly as I could^[idiomatic, "I was impatient"]. More than anything, I wanted to learn to read music, but in the beginning nobody even mentioned such a thing. The _chazan_ wasn't in any rush to train me. So I ingratiated myself with the other singers so they could teach me in secret. I would polish their shoes and clean their coats. It wasn't that I was a _miese yingl_^[miserable, pathetic boy]; they probably liked me - long story short, they gave me sheet music lessons without the _chazan_ knowing. I took to it so eagerly that in only four months I could read music excellently which for a nine-year-old _meshoyrer_ is an unusual thing. I was scared that when the _chazan_ discovered it, he would take action against me; I had made a mistake. Once when he caught me singing with sheet music with an older _meshoyrer_ who was teaching me, he wasn't just surprised but shocked - and he wasn't used to being surprised.

"'What kind of a voice is this?' he said. 

"'An older one^[more mature]', I replied.

"But it was an older _meshoyrer_ with a more mature voice, older than me. He used to sing solo. _Nu_, I was really jealous of him. But luckily for me, the older boy lowered his voice and stopped singing so I could take his place. I was so skilled at reading sheet music that they called me "Zeligel the sheet-music--devourer."

"And this comes in handy for you today still, when preparing music for a play?" the reporter asked.

"Yes, that's where I first learned to read music."

"Did the _chazan_ take your food away, as was customary at the time?"

"No, the _chazan_'s wife fed us well. She really was a good, smart woman. She truly understood singing and ran the entire business. Her husband was immersed in his _chazan_ duties. You have to understand, before I started singing solo, I ate in the kitchen with the younger other boys who were still learning. For the first time, I sat with everyone at the table now that I had become a soloist.

"Overall, the _chazan_'s wife treated me very well. The new boys' clothing were hand-me-downs from the older boys'. Didn't matter if what you were given is too wide or too long; you don't expect anything better than that. But she treated me better than the other boys. I recall how she looked at the time: a respectable and dignified, but worn, woman with a sympathetic face. 

"They used to only give underwear to the older boys, the tenors and basses. But she made an exception for me and made me a pair of underwear. She was afraid someone would snatch me away from them because the other _chazans_ were also interested in having me in their choirs. But she was so good to me. So, she made me a pair of underwear and after Shabbat dinner, I used to undress and go for a stroll around the house so everyone could see: Zelig had his own underwear.

"I was a little kid with little _peyes_" - Mogulesko added thoughtfully, looking at an old picture which was now coming to life in his mind's eye.

"In Belarusia, the _meshoyrim_ often accompanied the _chazan_ to different cities," the reporter remarked. "Did your _chazan_ also travel?"

"Just for Pesach, as I recall, he traveled with us to the [_rebbe_ Yochanan in Rakhmistrivka](https://en.wikipedia.org/wiki/Rachmastrivka_(Hasidic_dynasty))^[Offshoot of Chernobyl dynasty]. My mother had told me to try and get a charm^[e.g. a literal item] from the _rebbe_. We all knew that the _rebbe_ had quite the reputation, and me especially. The _rebbe_ gave each of us a ten-kopek coin, but he gave me twenty kopeks. You keep the coin for your whole life as a _segulah_^[used here to mean e.g. holy protective blessing]. Later in the street the _meshoyrim_ bought fruit, but I did't have any money besides the coin from the _rebbe_. I had my eye on a little watermelon...and eventually I gave in and bought it for five kopeks. I brought the 15 kopeks I had left back to my mother and lied to her that the _rebbe_ had given me 15 kopeks. She held onto those 15 holy kopeks for the rest of her life."

"How long did you stay with this first _chazan_?"

"Just for a short time. Another _chazan_ stole me away, 'ge-kidnapped' me. The story goes like this: one of the _meshoyrim_, Bochovetsky who later become a well-known opera singer, left to join the famous _chazan_ [Nisi from Kishinev](https://en.wikipedia.org/wiki/Nissan_Spivak) and persuaded me to go with him. But how did we handle this with the _chazan_'s wife? She wouldn't let me go, so we decided they would steal me away in he middle of the night. Everything had been prepared - a coachman who was in on the plan was waiting for us outside. I snuck out, just in my shoes and underwear, and the coachman threw a coat over me and took me to the town of Tyshlek where they bought me new things, and from there they took me to Kishinev. When I think about it now, I am ashamed of how I treated the _chazan_'s wife who really was so good to me. Today she is more sympathetic to me with her children. Her son is a doctor in Philadelphia, and one of her sons-in-law is a _chazan_ in Philadelphia[^wolf]. The latter is one of the [famous _chazan_ Minkowsky from Odessa's](https://en.wikipedia.org/wiki/Pinhas_Minkowsky) brothers, who is now the _chazan_ at the [Eldridge Street shul](https://www.eldridgestreet.org)."

"How much did Nisi pay you?"

"Ah, a lot of money! 60 rubles a year, and 12 kopeks on the rubel^[e.g., "12 cents on the dollar"] for a _meshoyrim_ really goes a long way. The famous _chazan_ Kuper, who passed away in New York a year ago, was Nisi's leading tenor at the time. Soon he took over as the lead _chazan_ in Bucharest, Roumania, and a few months later he came special to Kishinev where I was stolen away to. Nisi happened to be sitting _shiva_ at the time, but they weren't actively _davening_ so the timing turned out to be good. Kuper right away suggested 20 francs a month^[Apparently in the 1800s when Roumania introduced the leu currency, they aligned it to the standards from France; hence the term franc was sometimes used.], which is how I ended up in Roumania where I was fated to later become an actor."



[^wolf]: This is almost certainly Wolf Minkowsky. According to [Minkowsky family researchers](https://www.theminkshererfamilystory.com/blog/pinney-and-family): _Pichus’s older brother and the vanguard of the family, Wolf Minkowsky, 1858-1915, changed his name to Wilhelm Weintraub. According to Willhelm’s grandchildren, Bill and Mary Edda Gamson, Wilhelm and Marie Weintraub, first immigrated to Cleveland and then moved to Philadelphia. They lived at 304 South St, which was the destination of several family members who came to Philadelphia.  Wilhelm was the Chazzan at Kesher Israel, 438 Lombard St. which is an active Shul today.  Something happened and Wilhelm disassociated from Judaism and became “an outspoken atheist and leather merchant”  according to Bill Gamson his grandson._  As such, Mogulesko stayed on those pillows from his youth at 304 South St. 